Repository sofastack/sofa-tracer, pull requests merged in 2018-10, with the labels that each got.

#76 Add HttpClient Sample Quick Start
  pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  tracer-samples/pom.xml
  tracer-samples/tracer-sample-with-httpclient/README.md
  tracer-samples/tracer-sample-with-httpclient/pom.xml
  tracer-samples/tracer-sample-with-httpclient/src/main/java/com/alipay/sofa/tracer/examples/httpclient/HttpClientDemoApplication.java
  tracer-samples/tracer-sample-with-httpclient/src/main/java/com/alipay/sofa/tracer/examples/httpclient/controller/SampleRestController.java
  tracer-samples/tracer-sample-with-httpclient/src/main/java/com/alipay/sofa/tracer/examples/httpclient/instance/HttpAsyncClientInstance.java
  tracer-samples/tracer-sample-with-httpclient/src/main/java/com/alipay/sofa/tracer/examples/httpclient/instance/HttpClientInstance.java
  tracer-samples/tracer-sample-with-httpclient/src/main/resources/application.properties
Labels: enhancement

#82 Upgrade to snapshot version.
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-samples/pom.xml
  tracer-samples/tracer-sample-with-h2/pom.xml
  tracer-samples/tracer-sample-with-httpclient/README.md
  tracer-samples/tracer-sample-with-httpclient/pom.xml
  tracer-samples/tracer-sample-with-slf4j/pom.xml
  tracer-samples/tracer-sample-with-sofarpc/pom.xml
  tracer-samples/tracer-sample-with-springmvc/pom.xml
  tracer-samples/tracer-sample-with-zipkin/pom.xml
  tracer-sofa-boot-plugin/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: upgrade

#86 When use httpclient print log ,if server response blank fix caused NPE
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/src/main/java/com/alipay/sofa/tracer/plugins/httpclient/interceptor/AbstractHttpRequestInterceptor.java
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/src/test/java/com/alipay/sofa/tracer/plugins/httpclient/HttpClientTracerTest.java
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/src/test/java/com/alipay/sofa/tracer/plugins/httpclient/base/client/HttpClientInstance.java
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/src/test/java/com/alipay/sofa/tracer/plugins/httpclient/base/controller/SampleRestController.java
Labels: bug

#83 Fix datasource case exception
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/datasource/processor/DataSourceBeanFactoryPostProcessor.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/base/DatasourceBeanDefinitionRegistry.java
  tracer-sofa-boot-starter/src/test/resources/hikariDataSource.xml
Labels: bug

#100 Advance assembly of sofaTracerConfiguration.
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/configuration/SofaTracerAutoConfiguration.java
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/listener/SofaTracerConfigurationListener.java
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/properties/SofaTracerProperties.java
  tracer-sofa-boot-starter/src/main/resources/META-INF/spring.factories
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/ConfigurationTest.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/base/ConfigurationHolder.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/base/ConfigurationHolderListener.java
  tracer-sofa-boot-starter/src/test/resources/META-INF/spring.factories
  tracer-sofa-boot-starter/src/test/resources/application-config.properties
Labels: enhancement

#101 Pr/100
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/listener/SofaTracerConfigurationListener.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/config/ConfigurationTest.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/config/SofaTracerPropertiesTest.java
  tracer-sofa-boot-starter/src/test/resources/application-configerror.properties
Labels: enhancement

#105 Fix tracer log
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/initializer/SofaTracerInitializer.java
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/listener/SofaTracerConfigurationListener.java
  tracer-sofa-boot-starter/src/main/resources/META-INF/spring.factories
Labels: bug

#92 Upgrade 3.0.0-SNAPSHOT
  .travis.yml
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/src/test/java/com/alipay/sofa/tracer/plugins/httpclient/base/AbstractTestBase.java
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-core/src/test/java/com/alipay/common/tracer/core/base/AbstractTestBase.java
  tracer-extensions/pom.xml
  tracer-samples/pom.xml
  tracer-samples/tracer-sample-with-h2/README.md
  tracer-samples/tracer-sample-with-h2/pom.xml
  tracer-samples/tracer-sample-with-httpclient/README.md
  tracer-samples/tracer-sample-with-httpclient/pom.xml
  tracer-samples/tracer-sample-with-slf4j/README.md
  tracer-samples/tracer-sample-with-slf4j/pom.xml
  tracer-samples/tracer-sample-with-sofarpc/README.md
  tracer-samples/tracer-sample-with-sofarpc/pom.xml
  tracer-samples/tracer-sample-with-springmvc/README.md
  tracer-samples/tracer-sample-with-springmvc/pom.xml
  tracer-samples/tracer-sample-with-zipkin/README.md
  tracer-samples/tracer-sample-with-zipkin/pom.xml
  tracer-sofa-boot-plugin/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/listener/SofaTracerConfigurationListener.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/base/AbstractTestBase.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/config/SofaTracerPropertiesTest.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/zipkin/ZipkinSofaTracerSpanRemoteReporterTest.java
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: upgrade
