Repository sofastack/sofa-tracer, pull requests merged in 2018-08, with the labels that each got.

#46 SOFATracer version 2.1.2 for release
  pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-samples/pom.xml
  tracer-samples/tracer-sample-with-slf4j/pom.xml
  tracer-samples/tracer-sample-with-springmvc/pom.xml
  tracer-samples/tracer-sample-with-zipkin/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: upgrade

#45 add test case
  tracer-core/src/main/java/com/alipay/common/tracer/core/async/SofaTracerCallable.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/async/SofaTracerRunnable.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/async/TracedExecutorService.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/registry/AbstractTextB3Formatter.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/builder/XStringBuilderTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/file/CompositeTraceAppenderTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/manager/ConcurrentConsumerCorrectTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/manager/ConsumerExceptionHandlerTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/manager/StringConsumerExceptionHandlerTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/self/SelfLogTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/self/SynchronizingSelfLogTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/async/SofaTracerCallableTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/async/SofaTracerRunnableTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/async/TracedExecutorServiceTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/async/TracerScheduleExecutorServiceTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/exception/SamplingStrategyErrorExceptionTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/exception/SofaTracerRuntimeExceptionTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/exception/UnsupportedFormatExceptionTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/samplers/SamplerPropertiesTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/samplers/SamplingStatusTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/samplers/SofaTracerPercentageBasedSamplerTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/tracer/AbstractClientTracerTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/tracer/AbstractServerTracerTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/utils/CommonUtilsTest.java
  tracer-core/src/test/java/com/alipay/disruptor/AggregateEventHandlerTest.java
  tracer-core/src/test/java/com/alipay/disruptor/BusySpinWaitStrategyTest.java
  tracer-core/src/test/java/com/alipay/disruptor/EventPollerTest.java
  tracer-core/src/test/java/com/alipay/disruptor/FixedSequenceGroupTest.java
  tracer-core/src/test/java/com/alipay/disruptor/IgnoreExceptionHandlerTest.java
  tracer-core/src/test/java/com/alipay/disruptor/LiteTimeoutBlockingWaitStrategyTest.java
  tracer-core/src/test/java/com/alipay/disruptor/PhasedBackoffWaitStrategyTest.java
  tracer-core/src/test/java/com/alipay/disruptor/SequenceGroupTest.java
  tracer-core/src/test/java/com/alipay/disruptor/SleepingWaitStrategyTest.java
  tracer-core/src/test/java/com/alipay/disruptor/TimeoutBlockingWaitStrategyTest.java
  tracer-core/src/test/java/com/alipay/disruptor/WorkerPoolTest.java
  tracer-core/src/test/java/com/alipay/disruptor/YieldingWaitStrategyTest.java
  tracer-core/src/test/java/com/alipay/disruptor/dsl/WorkerPoolInfoTest.java
  tracer-core/src/test/java/com/alipay/disruptor/support/DummyEventHandler.java
  tracer-core/src/test/java/com/alipay/disruptor/support/DummySequenceBarrier.java
  tracer-core/src/test/java/com/alipay/disruptor/support/SequenceUpdater.java
  tracer-core/src/test/java/com/alipay/disruptor/support/TestEvent.java
  tracer-core/src/test/java/com/alipay/disruptor/support/WaitStrategyTestUtil.java
Labels: enhancement

#50 Use CAS operation to eliminate synchronized block
  tracer-core/src/main/java/com/alipay/common/tracer/core/samplers/SofaTracerPercentageBasedSampler.java
Labels: enhancement

#59 Upgrade 2.1.3
  pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-samples/pom.xml
  tracer-samples/tracer-sample-with-slf4j/pom.xml
  tracer-samples/tracer-sample-with-springmvc/pom.xml
  tracer-samples/tracer-sample-with-zipkin/pom.xml
  tracer-sofa-boot-plugin/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: upgrade

#60 Fix upgrade zipkin2
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/src/main/java/com/alipay/sofa/tracer/plugins/springmvc/SpringMvcSofaTracerFilter.java
  tracer-sofa-boot-starter/pom.xml
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/zipkin/ZipkinSofaTracerSpanRemoteReporter.java
Labels: bug, enhancement

#61 Cherry pick new ark plugin.
  pom.xml
  tracer-samples/tracer-sample-with-slf4j/README.md
  tracer-samples/tracer-sample-with-sofarpc/README.md
  tracer-samples/tracer-sample-with-springmvc/README.md
  tracer-samples/tracer-sample-with-zipkin/README.md
  tracer-sofa-boot-plugin/pom.xml
Labels: enhancement
