Repository sofastack/sofa-tracer, pull requests merged in 2019-10, with the labels that each got.

#282 fix ZipkinRestTemplateSender NAME.
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/src/main/java/com/alipay/sofa/tracer/plugins/zipkin/adapter/NetUtils.java
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/src/main/java/com/alipay/sofa/tracer/plugins/zipkin/adapter/ZipkinV2SpanAdapter.java
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/src/main/java/com/alipay/sofa/tracer/plugins/zipkin/sender/ZipkinRestTemplateSender.java
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/src/test/java/com/alipay/sofa/tracer/plugins/zipkin/ZipkinRestTemplateSenderTest.java
Labels: First-time contributor, bug, cla:yes, size/L

#284 upgrade-to-3.0.8-SNAPSHOT
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-2.6.x-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-flexible-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-samples/pom.xml
  tracer-samples/tracer-sample-with-dubbo/pom.xml
  tracer-samples/tracer-sample-with-dubbo/tracer-sample-with-dubbo-consumer/pom.xml
  tracer-samples/tracer-sample-with-dubbo/tracer-sample-with-dubbo-facade/pom.xml
  tracer-samples/tracer-sample-with-dubbo/tracer-sample-with-dubbo-provider/pom.xml
  tracer-samples/tracer-sample-with-h2/pom.xml
  tracer-samples/tracer-sample-with-httpclient/pom.xml
  tracer-samples/tracer-sample-with-openfeign/pom.xml
  tracer-samples/tracer-sample-with-openfeign/tracer-sample-with-openfeign-consumer/pom.xml
  tracer-samples/tracer-sample-with-openfeign/tracer-sample-with-openfeign-provider/pom.xml
  tracer-samples/tracer-sample-with-resttemplate/pom.xml
  tracer-samples/tracer-sample-with-sampler/pom.xml
  tracer-samples/tracer-sample-with-slf4j/pom.xml
  tracer-samples/tracer-sample-with-sofarpc/pom.xml
  tracer-samples/tracer-sample-with-springmvc/pom.xml
  tracer-samples/tracer-sample-with-zipkin/pom.xml
  tracer-sofa-boot-plugin/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: size/M

#288 Compatible-bed boot 3.2.0
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/listener/SofaTracerConfigurationListener.java
Labels: cla:yes, size/S
