Repository sofastack/sofa-tracer, pull requests merged in 2019-01, with the labels that each got.

#147 OpenTracingSpringMvcAutoConfiguration should add ConditionalOnClass
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/springmvc/configuration/OpenTracingSpringMvcAutoConfiguration.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/annotation/ExcludeClasses.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/condition/ConditionOnClassTest.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/junit/SeparateClassloaderTestRunner.java
Labels: bug

#158 Upgrade to 2.3.2 snapshot
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-samples/pom.xml
  tracer-samples/tracer-sample-with-h2/pom.xml
  tracer-samples/tracer-sample-with-httpclient/pom.xml
  tracer-samples/tracer-sample-with-resttemplate/pom.xml
  tracer-samples/tracer-sample-with-sampler/pom.xml
  tracer-samples/tracer-sample-with-slf4j/pom.xml
  tracer-samples/tracer-sample-with-sofarpc/pom.xml
  tracer-samples/tracer-sample-with-springmvc/pom.xml
  tracer-samples/tracer-sample-with-zipkin/pom.xml
  tracer-sofa-boot-plugin/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: upgrade

#161 Fix zipkin report samples rest
  tracer-samples/tracer-sample-with-zipkin/README.md
  tracer-samples/tracer-sample-with-zipkin/src/main/java/com/alipay/sofa/tracer/examples/zipkin/controller/SampleRestController.java
Labels: enhancement

#165 Fix spring mvc log print bug
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/src/main/java/com/alipay/sofa/tracer/plugins/springmvc/SpringMvcSofaTracerFilter.java
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/src/test/java/com/alipay/sofa/tracer/plugins/springmvc/AbstractTestBase.java
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/src/test/java/com/alipay/sofa/tracer/plugins/springmvc/SpringBootWebApplication.java
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/src/test/java/com/alipay/sofa/tracer/plugins/springmvc/SpringMvcSofaTracerFilterTest.java
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/src/test/resources/application.properties
  tracer-core/src/main/java/com/alipay/common/tracer/core/listener/SpanReportListenerHolder.java
Labels: bug

#156 Add OkHttp Plugin
  pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/main/java/com/alipay/sofa/tracer/plugins/okhttp/OkHttpDigestJsonEncoder.java
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/main/java/com/alipay/sofa/tracer/plugins/okhttp/OkHttpLogEnum.java
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/main/java/com/alipay/sofa/tracer/plugins/okhttp/OkHttpRequestCarrier.java
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/main/java/com/alipay/sofa/tracer/plugins/okhttp/OkHttpStatJsonReporter.java
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/main/java/com/alipay/sofa/tracer/plugins/okhttp/OkHttpTracer.java
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/main/java/com/alipay/sofa/tracer/plugins/okhttp/SofaTracerOkHttpBuilder.java
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/main/java/com/alipay/sofa/tracer/plugins/okhttp/interceptor/SofaTracerOkHttpInterceptor.java
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/main/resources/application.properties
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/test/java/com/alipay/sofa/tracer/plugins/okhttp/base/OkHttpTracerTest.java
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/test/java/com/alipay/sofa/tracer/plugins/okhttp/base/SpringBootWebApplication.java
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/test/java/com/alipay/sofa/tracer/plugins/okhttp/base/client/OkHttpClientInstance.java
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/test/java/com/alipay/sofa/tracer/plugins/okhttp/base/controller/PostBody.java
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/test/java/com/alipay/sofa/tracer/plugins/okhttp/base/controller/SampleRestController.java
Labels: enhancement, help wanted
