Repository sofastack/sofa-tracer, pull requests merged in 2019-02, with the labels that each got.

#171 Upgrade 2.3.3 snapshot version
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-samples/pom.xml
  tracer-samples/tracer-sample-with-h2/pom.xml
  tracer-samples/tracer-sample-with-httpclient/pom.xml
  tracer-samples/tracer-sample-with-resttemplate/pom.xml
  tracer-samples/tracer-sample-with-sampler/pom.xml
  tracer-samples/tracer-sample-with-slf4j/pom.xml
  tracer-samples/tracer-sample-with-sofarpc/pom.xml
  tracer-samples/tracer-sample-with-springmvc/pom.xml
  tracer-samples/tracer-sample-with-zipkin/pom.xml
  tracer-sofa-boot-plugin/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: upgrade

#169 improve the performance of SofaTracerPercentageBasedSampler
  tracer-core/src/main/java/com/alipay/common/tracer/core/samplers/SofaTracerPercentageBasedSampler.java
Labels: enhancement

#173 Fix OkHttpTracer don't send log to Zipkin bug
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/src/main/java/com/alipay/sofa/tracer/plugins/okhttp/interceptor/SofaTracerOkHttpInterceptor.java
Labels: bug

#172 Enhancement sofatracer runnable
  tracer-core/src/main/java/com/alipay/common/tracer/core/async/SofaTracerCallable.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/async/SofaTracerRunnable.java
  tracer-extensions/pom.xml
  tracer-extensions/src/test/java/com/alipay/common/tracer/extensions/log/MDCSpanExtensionTest.java
  tracer-samples/tracer-sample-with-slf4j/src/main/java/com/alipay/sofa/tracer/examples/slf4j/controller/SampleRestController.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/springmvc/SpringMvcFilterJsonOutputTest.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/springmvc/SpringMvcFilterTest.java
Labels: enhancement
