Repository sofastack/sofa-tracer, pull requests merged in 2020-12, with the labels that each got.

#397 Fixes gh-396
  sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/src/main/java/com/sofa/alipay/tracer/plugins/kafkamq/factories/SofaTracerKafkaConsumerFactory.java
  sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/src/main/java/com/sofa/alipay/tracer/plugins/kafkamq/producer/SofaTracerKafkaProducer.java
Labels: cla:yes, size/M

#395 Fixes gh-369
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/src/main/java/com/alipay/sofa/tracer/plugins/datasource/SmartDataSource.java
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/src/main/java/com/alipay/sofa/tracer/plugins/datasource/utils/DataSourceUtils.java
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/src/test/java/com/sofa/tracer/plugins/datasource/OracleTnsTest.java
Labels: cla:yes, size/L

#311 Xf/redis
  .gitignore
  pom.xml
  sofa-tracer-plugins/sofa-tracer-redis-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/SofaTracerRCFBeanPostProcessor.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/TracingRedisConnectionFactory.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/common/Action.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/common/RedisActionWrapperHelper.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/common/RedisCommand.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/common/ThrowingAction.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/common/ThrowingSupplier.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/connections/TracingReactiveRedisClusterConnection.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/connections/TracingReactiveRedisConnection.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/connections/TracingRedisClusterConnection.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/connections/TracingRedisConnection.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/connections/TracingRedisSentinelConnection.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/encoder/RedisDigestEncoder.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/encoder/RedisDigestJsonEncoder.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/enums/RedisLogEnum.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/reporter/RedisStatJsonReporter.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/reporter/RedisStatReporter.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/tracer/RedisSofaTracer.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/appender/file/TimedRollingFileAppender.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/constants/ComponentNameConstants.java
  tracer-core/src/main/java/com/alipay/disruptor/dsl/Disruptor.java
  tracer-sofa-boot-starter/pom.xml
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/redis/configuration/SofaTracerRedisConfiguration.java
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/redis/package-info.java
  tracer-sofa-boot-starter/src/main/resources/META-INF/spring.factories
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/redis/SofaTracerRedisConnectionTest.java
  tracer-sofa-boot-starter/src/test/resources/application-redis.properties
Labels: cla:yes, size/XXL

#318 bug fix # 312 SofaTracerFeignClient is unsupported when accessing directly using feign url and using link tracking times ...
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/src/main/java/com/alipay/sofa/tracer/plugins/springcloud/instruments/feign/SofaTracerFeignClient.java
Labels: First-time contributor, bug, cla:yes, question, size/S

#405 Create build.yml
  .github/workflows/build.yml
Labels: cla:yes, size/S

#407 fix test case
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/springmvc/SpringMvcFilterJsonOutputTest.java
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/springmvc/SpringMvcFilterTest.java
Labels: bug, cla:yes, size/M

#401 Fixes gh-376
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/src/main/java/com/alipay/sofa/tracer/plugins/springmvc/SpringMvcDigestEncoder.java
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/src/main/java/com/alipay/sofa/tracer/plugins/springmvc/SpringMvcDigestJsonEncoder.java
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/src/main/java/com/alipay/sofa/tracer/plugins/springmvc/SpringMvcSofaTracerFilter.java
Labels: cla:yes, size/S

#403 Fixes gh-402
  sofa-tracer-plugins/sofa-tracer-mongodb-plugin/src/main/java/com/alipay/sofa/tracer/plugins/mongodb/tracers/MongoClientTracer.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/constants/ComponentNameConstants.java
Labels: cla:yes, size/XS

#408 junit、log4j2 version to update
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: cla:yes, size/XS

#409 update icon
  README.md
Labels: cla:yes, size/XS

#334 Fixes gh-308
  tracer-core/src/main/java/com/alipay/common/tracer/core/configuration/SofaTracerConfiguration.java
  tracer-sofa-boot-starter/src/main/java/com/alipay/sofa/tracer/boot/datasource/processor/DataSourceBeanFactoryPostProcessor.java
Labels: First-time contributor, cla:yes, size/M

#411 datasource escape with special check like newline
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/src/main/java/com/alipay/sofa/tracer/plugins/datasource/utils/SqlUtils.java
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/src/test/java/com/sofa/tracer/plugins/datasource/DataSourceUtilTest.java
Labels: First-time contributor, cla:yes, size/M

#412 optimized code
  pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-2.6.x-plugin/src/main/java/com/alipay/sofa/tracer/plugins/dubbo/DubboSofaTracerFilter.java
  sofa-tracer-plugins/sofa-tracer-dubbo-common-plugin/src/main/java/com/alipay/sofa/tracer/plugins/dubbo26x/DubboSofaTracerFilter.java
  sofa-tracer-plugins/sofa-tracer-dubbo-common-plugin/src/main/java/com/alipay/sofa/tracer/plugins/dubbo27x/DubboSofaTracerFilter.java
  sofa-tracer-plugins/sofa-tracer-dubbo-plugin/src/main/java/com/alipay/sofa/tracer/plugins/dubbo/DubboSofaTracerFilter.java
  sofa-tracer-plugins/sofa-tracer-flexible-plugin/src/main/java/com/alipay/sofa/tracer/plugin/flexible/FlexibleTracer.java
  tracer-core/pom.xml
  tracer-core/src/main/java/com/alipay/common/tracer/core/SofaTracer.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/appender/file/TimedRollingFileAppender.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/configuration/SofaTracerConfiguration.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/constants/SofaTracerConstant.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/reporter/common/CommonTracerManager.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/span/SofaTracerSpan.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/tags/SpanTags.java
  tracer-core/src/main/resources/tracer/log-codes.properties
  tracer-core/src/main/resources/tracer/log-codes_zh_CN.properties
Labels: cla:yes, size/L
