Repository sofastack/sofa-tracer, pull requests merged in 2021-04, with the labels that each got.

#433 add desensitization extension
  tracer-core/src/main/java/com/alipay/common/tracer/core/appender/self/SelfLog.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/configuration/SofaTracerConfiguration.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/middleware/parent/AbstractDigestSpanEncoder.java
  tracer-core/src/main/java/com/alipay/common/tracer/util/CoolDown.java
  tracer-core/src/main/java/com/alipay/common/tracer/util/DesensitizationHelper.java
  tracer-core/src/main/java/com/alipay/common/tracer/util/Desensitizer.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/self/SelfLogTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/configuration/SofaTracerConfigurationTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/util/CoolDownTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/util/DesensitizationHelperTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/util/MockDesensitizer.java
Labels: cla:yes, size/L

#434 update to 3.1.1
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-2.6.x-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-common-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-flexible-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-mongodb-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rabbitmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-redis-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rocketmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmessage-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: cla:yes, size/M

#430 Support logging.file.path
  .gitignore
  tracer-core/src/main/java/com/alipay/common/tracer/core/appender/TracerLogRootDaemon.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/TracerLogRootDaemonLoggingpathTest.java
Labels: cla:yes, enhancement, size/M

#427 Speed up test case by remove sleep code
  tracer-core/src/main/java/com/alipay/common/tracer/core/reporter/digest/DiskReporterImpl.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/TestUtil.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/file/TimedRollingFileAppenderTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/info/StaticInfoLogTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/manager/ConcurrentConsumerCorrectTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/manager/ConcurrentDiscardTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/manager/ConsumerExceptionHandlerTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/manager/StringConsumerExceptionHandlerTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/appender/self/SelfLogTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/reporter/common/CommonSpanEncoderTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/reporter/common/CommonTracerManagerTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/reporter/digest/DiskReporterImplTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/span/SofaTracerSpanTest.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/tracertest/SofaTracerTest.java
Labels: cla:yes, performance, size/XL
