Repository sofastack/sofa-tracer, pull requests merged in 2022-08, with the labels that each got.

#492 fix ut issue
  tracer-sofa-boot-starter/src/test/java/com/alipay/sofa/tracer/boot/config/ConfigurationTest.java
  tracer-sofa-boot-starter/src/test/resources/application.properties
Labels: bug, cla:yes, size/XS

#486 Fix the problem of using a higher version of feign
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/src/main/java/com/alipay/sofa/tracer/plugins/springcloud/carriers/FeignRequestHeadersCarrier.java
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/src/main/java/com/alipay/sofa/tracer/plugins/springcloud/instruments/feign/SofaTracerFeignClient.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/registry/AbstractTextB3Formatter.java
Labels: cla:yes, size/M

#493 support origin traceId and spanId to zipkin tags
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/src/main/java/com/alipay/sofa/tracer/plugins/zipkin/adapter/ZipkinV2SpanAdapter.java
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/src/test/java/com/alipay/sofa/tracer/plugins/zipkin/ZipkinV2SpanAdapterTest.java
Labels: cla:yes, size/XS

#494 Added shadowtest support
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/src/main/java/com/alipay/sofa/tracer/plugins/zipkin/adapter/ZipkinV2SpanAdapter.java
Labels: cla:yes, size/S

#496 Restore parent span for redis plugin
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/common/RedisActionWrapperHelper.java
Labels: cla:yes, size/M

#497 upgrade to 3.1.3-SNAPSHOT
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-2.6.x-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-common-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-flexible-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-mongodb-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rabbitmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-redis-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rocketmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmessage-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: cla:yes, size/M
