Repository sofastack/sofa-tracer, pull requests merged in 2024-08, with the labels that each got.

#532 update tracer version to 3.1.6-SNAPSHOT
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-2.6.x-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-common-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-flexible-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-mongodb-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rabbitmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-redis-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rocketmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmessage-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: cla:yes, size/M, First-time contributor

#531 enhance escape and replace method.
  tracer-core/src/main/java/com/alipay/common/tracer/core/appender/builder/XStringBuilder.java
  tracer-core/src/main/java/com/alipay/common/tracer/core/utils/StringUtils.java
  tracer-core/src/test/java/com/alipay/common/tracer/core/utils/StringUtilsTest.java
Labels: cla:yes, size/L, First-time contributor

#533 update tracer to release 3.1.6
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-2.6.x-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-common-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-flexible-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-mongodb-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rabbitmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-redis-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rocketmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmessage-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: cla:yes, size/M

#537 fix the MDC leakage issue.
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-2.6.x-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-common-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-flexible-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-mongodb-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rabbitmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-redis-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rocketmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmessage-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-core/src/main/java/com/alipay/common/tracer/core/async/FunctionalAsyncSupport.java
  tracer-extensions/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: bug, cla:yes, size/M

#536 Fix tracer runnable mdc clean
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-2.6.x-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-common-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-flexible-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-mongodb-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rabbitmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-redis-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rocketmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmessage-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-core/src/main/java/com/alipay/common/tracer/core/async/FunctionalAsyncSupport.java
  tracer-extensions/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: bug, cla:yes, size/M

#538 Fix unit tests for 4.x branch
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/src/test/java/com/sofa/tracer/plugins/datasource/base/BaseTest.java
  sofa-tracer-plugins/sofa-tracer-dubbo-2.6.x-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rabbitmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-core/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: bug, cla:yes, size/M
