Repository sofastack/sofa-tracer, pull requests merged in 2024-12, with the labels that each got.

#550 fix redis trace plugin
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/common/RedisActionWrapperHelper.java
  sofa-tracer-plugins/sofa-tracer-redis-plugin/src/main/java/com/sofa/alipay/tracer/plugins/spring/redis/tracer/RedisSofaTracer.java
Labels: bug, cla:yes, size/L, First-time contributor

#552 change tag to 3.1.9-SNAPSHOT
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-2.6.x-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-common-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-flexible-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-mongodb-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rabbitmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-redis-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rocketmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmessage-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: cla:yes, size/M, First-time contributor

#553 change tag to 3.1.9
  pom.xml
  sofa-tracer-plugins/sofa-tracer-datasource-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-2.6.x-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-common-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-dubbo-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-flexible-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-httpclient-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-kafkamq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-mongodb-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-okhttp-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rabbitmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-redis-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-resttmplate-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-rocketmq-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-spring-cloud-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmessage-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-springmvc-plugin/pom.xml
  sofa-tracer-plugins/sofa-tracer-zipkin-plugin/pom.xml
  tracer-all/pom.xml
  tracer-core/pom.xml
  tracer-extensions/pom.xml
  tracer-sofa-boot-starter/pom.xml
  tracer-test/core-test/pom.xml
  tracer-test/log4j-test/pom.xml
  tracer-test/log4j2-test/pom.xml
  tracer-test/logback-test/pom.xml
Labels: cla:yes, size/M
